name: Deploy Astro Website

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Bun (the JavaScript runtime)
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Add Bun to the PATH (so that it can be used in subsequent steps)
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Install dependencies using Bun
      - name: Install dependencies
        run: bun install

      # Build the Astro project using Bun
      - name: Build the Astro project
        run: bun run build

      # Deploy to GitHub Pages (using the latest stable version of the deploy action)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Updated version
        with:
          branch: gh-pages  # The branch that will be used to deploy
          folder: dist  # The folder that contains the built Astro site
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
