name: Deploy Astro Website

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the `main` branch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (ensure the version matches the one in your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Or use the version that your Astro project requires

      # Install Yarn (if not already installed)
      - name: Install Yarn
        run: npm install --global yarn

      # Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install

      # Build the Astro project using Yarn
      - name: Build the Astro project
        run: yarn build

      # Deploy to GitHub Pages (using the latest stable version of the deploy action)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Updated version
        with:
          branch: gh-pages  # The branch that will be used to deploy
          folder: dist  # The folder that contains the built Astro site
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
